name: voc-imagecropper
channels:
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python>=3.8
  - jupyter
  - ipykernel
  - sagemaker
  - tensorflow
  - pip
  - pip:
    - -r requirements.txt
