name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: semantic
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code and all tags and branches
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        continue-on-error: true
        with:
          context: .
          push: true
          tags: |
            mbari/voc-imagecropper:latest
          labels: |
            IMAGE_URI=mbari/voc-imagecropper
            
      - name: Build and push arm64 abd amd64 images to Docker Hub
        uses: docker/build-push-action@v3
        continue-on-error: true
        with:
          context: .
          push: true
          tags: |
            mbari/voc-imagecropper:latest
          labels: |
            IMAGE_URI=mbari/voc-imagecropper
          platforms: linux/arm/v8,linux/amd64,linux/arm64
