name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  semantic_release:
    runs-on: ubuntu-latest
    name: Runs semantic release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: semantic
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: docker push version
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} 
          docker buildx create --name mybuilder --platform linux/arm/v8,linux/amd64,linux/arm64 --use
          docker buildx build --push --platform linux/arm/v8,linux/amd64,linux/arm64 -t mbari/voc-imagecropper:$RELEASE_VERSION --label IMAGE_URI=mbari/voc-imagecropper:$RELEASE_VERSION .